
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Chanith randiv
 */
public class Bill extends javax.swing.JFrame {
    
    private JTextArea billTextArea;
    private JLabel totalLabel;
    private JScrollPane scrollPane;

    /**
     * Creates new form Bill
     * @param billDetails
     */
    
     public Bill(String billDetails,double total ) {
        
        setupUI(billDetails, total);
       
        
    }
    public Bill() {
        initComponents();
    }

  
     private void setupUI(String billDetails,double total){
        setTitle("Generated Bill");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(600, 500);
        setLayout(new BorderLayout(10,10));
        
        billTextArea = new JTextArea(billDetails,20,40);
        billTextArea.setEditable(false);
        billTextArea.setFont(new Font("Monospaced",Font.PLAIN,14));
        scrollPane=new JScrollPane(billTextArea);
        scrollPane.setBorder(BorderFactory.createTitledBorder("Bill Details"));
        add(scrollPane,BorderLayout.CENTER);
        
        JPanel bottomPanel = new JPanel(new BorderLayout(10,10));
        
        totalLabel = new JLabel("TOTAL: Rs" +String.format("%.2f", total));
        totalLabel.setFont(new Font("SansSerif",Font.BOLD,18));
        totalLabel.setHorizontalAlignment(SwingConstants.RIGHT);
        bottomPanel.add(totalLabel, BorderLayout.WEST);
        
         JButton viewDbButton = new JButton("View Database");
         viewDbButton.setFont(new Font("SansSerif", Font.PLAIN, 14));
         viewDbButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new ViewDatabase().setVisible(true);
            }
        });
        bottomPanel.add(viewDbButton, BorderLayout.EAST);

        add(bottomPanel, BorderLayout.SOUTH); // IMPORTANT: add bottomPanel to frame

        setLocationRelativeTo(null);
        setVisible(true);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
