/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Chanith randiv
 */

import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;

public class PizzaHouseBuyPage extends javax.swing.JFrame {

    /**
     * Creates new form PizzaHouseBuyPage
     */
    
    
    class Meal {
        String name;
        double price;
        
        public Meal(String name, double price) {
            this.name = name;
            this.price = price;
        }
    }
    
    class OrderItem {
        Meal meal;
        int quantity;
        
        public OrderItem(Meal meal, int quantity) {
            this.meal = meal;
            this.quantity = quantity;
        }
    }
    
    private ArrayList<OrderItem> orderItems = new ArrayList<>();
    private final JPanel addDisplayPanal;
    private int totalAmount = 0;
    private final java.util.HashMap<String, Double> mealPrices = new java.util.HashMap<>();
    DefaultComboBoxModel<String> large;
    DefaultComboBoxModel<String> small;
    
    
    public PizzaHouseBuyPage() {
        
        initComponents();
        
        mealPrices.put("Chicken Pizza", 20.0);      //Chicken Pizza          
//Fish Pizza
//BBQ Pizza
//Mix Pizza
//Mashroom Pizza
        
        mealPrices.put("L Fish Pizza Rs 600/-", 600.0);
        mealPrices.put("L BBQ Pizza Rs 800/-", 800.0);
        mealPrices.put("L Mix Pizza Rs 1000/-", 1000.0);
        mealPrices.put("L Mashroom Pizza Rs 1200/-", 1200.0);
        
        mealPrices.put("S Fish Pizza Rs 500/-", 500.0);
        mealPrices.put("S BBQ Pizza Rs 700/-", 700.0);
        mealPrices.put("S Mix Pizza Rs 800/-", 800.0);
        mealPrices.put("S Mashroom Pizza Rs 1000/-", 1000.0);
       

        large= new DefaultComboBoxModel<>(new String[]{"L Fish Pizza Rs 600/-","L BBQ Pizza Rs 800/-","L Mix Pizza Rs 1000/-","L Mashroom Pizza Rs 1200/-"});
        small = new DefaultComboBoxModel<>(new String[]{"S Fish Pizza Rs 500/-", "S BBQ Pizza Rs 700/-", "S Mix Pizza Rs 800/-","S Mashroom Pizza Rs 1000/-"});
       
        addDisplayPanal = new JPanel();
        addDisplayPanal.setLayout(new BoxLayout(addDisplayPanal, BoxLayout.Y_AXIS));
        JScrollPane scrollPane = new JScrollPane(addDisplayPanal);
        scrollPane.setBounds(650, 80, 500, 180);
        add(scrollPane);

        sizeComboBox.addItem("Large");
        sizeComboBox.addItem("Small");
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sizeComboBox = new javax.swing.JComboBox<>();
        Tottxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qtxt = new javax.swing.JTextField();
        mealComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calButton.setText("Calculate");
        calButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calButtonActionPerformed(evt);
            }
        });

        subButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subButton.setText("Submit");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel1.setText("Meal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Total Amount");

        sizeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeComboBoxActionPerformed(evt);
            }
        });

        Tottxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Quantity");

        qtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mealComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mealComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setText("Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sizeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tottxt)
                            .addComponent(qtxt)
                            .addComponent(mealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tottxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeComboBoxActionPerformed
        // TODO add your handling code here:
        
         String selected = (String) sizeComboBox.getSelectedItem();
            if (selected.equals("Large")){
                mealComboBox.setModel(large);
                
            }else if (selected.equals("Small")){
                mealComboBox.setModel(small);
            }
            
            
        
            
    }//GEN-LAST:event_sizeComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        addDisplayPanal.removeAll();
        addDisplayPanal.revalidate();
        addDisplayPanal.repaint();
        totalAmount = 0;
        Tottxt.setText("");
        orderItems.clear();
                
        
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
        // TODO add your handling code here:
        
           if (orderItems.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No items to submit", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        StringBuilder receipt = new StringBuilder("===== MEAL RECEIPT =====\n\n");
        double total = 0.0;
        
        for (OrderItem item : orderItems) {
            double itemTotal = item.meal.price * item.quantity;
            receipt.append(String.format("%-15s x %-3d = Rs %6.2f\n", 
                item.meal.name, item.quantity, itemTotal));
            total += itemTotal;
        }
        receipt.append("\n=========================\n");
        receipt.append(String.format("TOTAL: Rs %.2f", total));
        
        Bill billFrame = new Bill (receipt.toString(), total);
        billFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_subButtonActionPerformed

    private void calButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calButtonActionPerformed
        // TODO add your handling code here:
        
        String mealName = (String) mealComboBox.getSelectedItem();
        String qtyStr = qtxt.getText();

        try {
            int qty = Integer.parseInt(qtyStr);
            Double price = mealPrices.get(mealName);
            
            if (price == null) {
                JOptionPane.showMessageDialog(this, "Invalid medicine selected!");
                return;
            }
            
            Meal med = new Meal(mealName, price);
            OrderItem item = new OrderItem(med, qty);
            orderItems.add(item);
            
            int itemTotal = (int) (price * qty);
            totalAmount += itemTotal;

            // Display medicine in panel
            JPanel rowPanel = new JPanel();
            rowPanel.setLayout(new GridLayout(1, 3));
            rowPanel.setMaximumSize(new Dimension(480, 25));
            rowPanel.add(new JLabel("Meal " + mealName));
            rowPanel.add(new JLabel("Qty: " + qty));
            rowPanel.add(new JLabel("Rs. " + itemTotal));

            addDisplayPanal.add(rowPanel);
            addDisplayPanal.revalidate();
            addDisplayPanal.repaint();

            // Show total
            Tottxt.setText("Rs. " + totalAmount);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid quantity!");
        }
        
          

    }//GEN-LAST:event_calButtonActionPerformed

    private void mealComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaHouseBuyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaHouseBuyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaHouseBuyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaHouseBuyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaHouseBuyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tottxt;
    private javax.swing.JButton calButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> mealComboBox;
    private javax.swing.JTextField qtxt;
    private javax.swing.JComboBox<String> sizeComboBox;
    private javax.swing.JButton subButton;
    // End of variables declaration//GEN-END:variables
}
